Update code-of-conduct.md
docker/code-of-conduct pull request #9
Opened 2016-10-26 13:53 UTC by arielelkin

2016-11-15 22:12 UTC, arielelkin commented
bump.

2024-09-30 03:29 UTC, Jekyle approved these changes

2024-10-23 16:29 UTC, sanscontext requested changes
These changes were never approved by the organizers, and should not be incorporated into the corpus. I would close this if I could.

2024-11-19 12:06 UTC, closed without merging

2024-11-19 12:06 UTC, thaJeztah commented
Yup, let me close this one